/* AUTO-GENERATED by setup.js — do not edit manually */
window.SUPABASE_CONFIG = {
  url     : 'https://xoochhcyyaxjlwldqaqy.supabase.co',
  anonKey : 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvb2NoaGN5eWF4amx3bGRxYXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2ODcyODUsImV4cCI6MjA5MDI2MzI4NX0.9eluNAkazSkSBarnETPJupeBrPKG12WW8zPSH0B0UE0'
};
