/* AUTO-GENERATED by setup.js — do not edit manually */
/* Run: node setup.js after filling in .env         */
window.SUPABASE_CONFIG = {
  url     : 'YOUR_SUPABASE_URL',
  anonKey : 'YOUR_SUPABASE_ANON_KEY'
};
