#!/usr/bin/env node
/* ─────────────────────────────────────────────────────────
   setup.js — Run once after filling in .env
   Generates:
     js/supabase-config.js   (Supabase credentials)
     js/admin-config.js      (Admin email + password hash)

   Usage:
     node setup.js
─────────────────────────────────────────────────────────── */
const fs     = require('fs');
const path   = require('path');
const crypto = require('crypto');

/* ── Read env — process.env first (Vercel), then .env file ── */
const env = Object.assign({}, process.env);

const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf8').split('\n').forEach(line => {
    line = line.trim();
    if (!line || line.startsWith('#')) return;
    const i = line.indexOf('=');
    if (i < 0) return;
    const k = line.slice(0, i).trim();
    if (!env[k]) env[k] = line.slice(i + 1).trim(); // process.env takes precedence
  });
}

/* ── Validate ──────────────────────────────────────────── */
const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'ADMIN_EMAIL', 'ADMIN_PASSWORD'];
const missing  = required.filter(k => !env[k] || env[k].startsWith('YOUR_'));
if (missing.length) {
  console.error('ERROR: Fill in these fields in .env first:\n  ' + missing.join('\n  '));
  process.exit(1);
}

/* ── Hash password (SHA-256, same as the browser uses) ─── */
const passHash = crypto.createHash('sha256').update(env.ADMIN_PASSWORD).digest('hex');

/* ── Write js/supabase-config.js ───────────────────────── */
const supabaseCfg =
`/* AUTO-GENERATED by setup.js — do not edit manually */
window.SUPABASE_CONFIG = {
  url     : '${env.SUPABASE_URL}',
  anonKey : '${env.SUPABASE_ANON_KEY}'
};
`;
fs.writeFileSync(path.join(__dirname, 'js', 'supabase-config.js'), supabaseCfg);
console.log('✓ js/supabase-config.js written');

/* ── Write js/admin-config.js ──────────────────────────── */
const adminCfg =
`/* AUTO-GENERATED by setup.js — do not edit manually */
window.ADMIN_CONFIG = {
  email   : '${env.ADMIN_EMAIL}',
  passHash: '${passHash}'
};
`;
fs.writeFileSync(path.join(__dirname, 'js', 'admin-config.js'), adminCfg);
console.log('✓ js/admin-config.js written');

console.log('\nDone. Refresh your browser (Cmd+Shift+R) to apply changes.');
